kind: Deployment
apiVersion: apps/v1
metadata:
  name: kusama-slot-backend
  namespace: chainx-pre
  labels:
    app: kusama-slot-backend
  annotations:
    deployment.kubernetes.io/revision: '3'
    kubesphere.io/alias-name: kusama-slot-backend-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kusama-slot-backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kusama-slot-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: container-kusama-slot-backend-pre
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-main
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mongodb-pre
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
